### ISSUE TITLE
Gazebo emulation problem

### ISSUE THREAD

**Issue by Azircarry** [uzh-rpg/data_driven_mpc#16]
When I go to the gazebo simulation, I get the following problem.
The previous ones are all running out, but when I run the following command 

roslaunch ros_gp_mpc gp_mpc_wrapper.launch recording:=True dataset_name:=gazebo_dataset environment:=gazebo flight_mode:=random n_seeds:=10

I get the following error.can you help me,please
![d097a18f415711b535f0d9e3fd46b3b](https://github.com/uzh-rpg/data_driven_mpc/assets/114214508/85ed1390-5a9a-4c95-b75e-e0789c810bd1)

**Comment by 1092281350** [comment]
I have the same problem with you.I am in Ubuntu18.04,could you solved it?

**Comment by Azircarry** [comment]
> I have the same problem with you.I am in Ubuntu18.04,could you solved it?

No, I really want to fix it! I need someone to help me

**Comment by 1092281350** [comment]
> > I have the same problem with you.I am in Ubuntu18.04,could you solved it?
> 
> No, I really want to fix it! I need someone to help me

OK,we can keep in touch,If I solved I will tell you.

**Comment by Azircarry** [comment]
> > > I have the same problem with you.I am in Ubuntu18.04,could you solved it?
> > 
> > 
> > No, I really want to fix it! I need someone to help me
> 
> OK,we can keep in touch,If I solved I will tell you.

OK.I'm also ubuntu18.04 system. I may also test it on ubuntu20.04 and I'll keep you informed when the results are available. Stay in touch and thank you for your cooperation

**Comment by Azircarry** [comment]
> > > > I have the same problem with you.I am in Ubuntu18.04,could you solved it?
> > > 
> > > 
> > > No, I really want to fix it! I need someone to help me
> > 
> > 
> > OK,we can keep in touch,If I solved I will tell you.
> 
> OK.I'm also ubuntu18.04 system. I may also test it on ubuntu20.04 and I'll keep you informed when the results are available. Stay in touch and thank you for your cooperation

秦志浩？

**Comment by 1092281350** [comment]
yes,你是？

**Comment by Azircarry** [comment]
> yes,你是？

我看你邮箱，觉得你是中国人，哈哈，我叫张新宇

**Comment by 1092281350** [comment]
> > > > > I have the same problem with you.I am in Ubuntu18.04,could you solved it?
> > > > 
> > > > 
> > > > No, I really want to fix it! I need someone to help me
> > > 
> > > 
> > > OK,we can keep in touch,If I solved I will tell you.
> > 
> > 
> > OK.I'm also ubuntu18.04 system. I may also test it on ubuntu20.04 and I'll keep you informed when the results are available. Stay in touch and thank you for your cooperation
> 
> 秦志浩？



> > yes,你是？
> 
> 我看你邮箱，觉得你是中国人，哈哈，我叫张新宇

哈哈，我看你的ubuntu界面有个zh，也觉得你是中国人，但你的英文有点不像。能加个qq吗

**Comment by Azircarry** [comment]
> > yes,你是？
> 
> 我看你邮箱，觉得你是中国人，哈哈

> > > > > > I have the same problem with you.I am in Ubuntu18.04,could you solved it?
> > > > > 
> > > > > 
> > > > > No, I really want to fix it! I need someone to help me
> > > > 
> > > > 
> > > > OK,we can keep in touch,If I solved I will tell you.
> > > 
> > > 
> > > OK.I'm also ubuntu18.04 system. I may also test it on ubuntu20.04 and I'll keep you informed when the results are available. Stay in touch and thank you for your cooperation
> > 
> > 
> > 秦志浩？
> 
> > > yes,你是？
> > 
> > 
> > 我看你邮箱，觉得你是中国人，哈哈，我叫张新宇
> 
> 哈哈，我看你的ubuntu界面有个zh，也觉得你是中国人，但你的英文有点不像。能加个qq吗

932474071，备注一下啊

**Comment by kingdom-l** [comment]
> > > yes,你是？
> > 
> > 
> > 我看你邮箱，觉得你是中国人，哈哈
> 
> > > > > > > I have the same problem with you.I am in Ubuntu18.04,could you solved it?
> > > > > > 
> > > > > > 
> > > > > > No, I really want to fix it! I need someone to help me
> > > > > 
> > > > > 
> > > > > OK,we can keep in touch,If I solved I will tell you.
> > > > 
> > > > 
> > > > OK.I'm also ubuntu18.04 system. I may also test it on ubuntu20.04 and I'll keep you informed when the results are available. Stay in touch and thank you for your cooperation
> > > 
> > > 
> > > 秦志浩？
> > 
> > 
> > > > yes,你是？
> > > 
> > > 
> > > 我看你邮箱，觉得你是中国人，哈哈，我叫张新宇
> > 
> > 
> > 哈哈，我看你的ubuntu界面有个zh，也觉得你是中国人，但你的英文有点不像。能加个qq吗
> 
> 932474071，备注一下啊

hello，你最终跑出来了吗？我卡在gazebo那部分“Run a Circle trajectory with correction”

**Comment by kingdom-l** [comment]
> > > > > > I have the same problem with you.I am in Ubuntu18.04,could you solved it?
> > > > > 
> > > > > 
> > > > > No, I really want to fix it! I need someone to help me
> > > > 
> > > > 
> > > > OK,we can keep in touch,If I solved I will tell you.
> > > 
> > > 
> > > OK.I'm also ubuntu18.04 system. I may also test it on ubuntu20.04 and I'll keep you informed when the results are available. Stay in touch and thank you for your cooperation
> > 
> > 
> > 秦志浩？
> 
> > > yes,你是？
> > 
> > 
> > 我看你邮箱，觉得你是中国人，哈哈，我叫张新宇
> 
> 哈哈，我看你的ubuntu界面有个zh，也觉得你是中国人，但你的英文有点不像。能加个qq吗

hello，你最终跑出来了吗？我卡在gazebo那部分“Run a Circle trajectory with correction”

**Comment by Azircarry** [comment]
> > > > > > > I have the same problem with you.I am in Ubuntu18.04,could you solved it?
> > > > > > 
> > > > > > 
> > > > > > No, I really want to fix it! I need someone to help me
> > > > > 
> > > > > 
> > > > > OK,we can keep in touch,If I solved I will tell you.
> > > > 
> > > > 
> > > > OK.I'm also ubuntu18.04 system. I may also test it on ubuntu20.04 and I'll keep you informed when the results are available. Stay in touch and thank you for your cooperation
> > > 
> > > 
> > > 秦志浩？
> > 
> > 
> > > > yes,你是？
> > > 
> > > 
> > > 我看你邮箱，觉得你是中国人，哈哈，我叫张新宇
> > 
> > 
> > 哈哈，我看你的ubuntu界面有个zh，也觉得你是中国人，但你的英文有点不像。能加个qq吗
> 
> hello，你最终跑出来了吗？我卡在gazebo那部分“Run a Circle trajectory with correction”

能出来一部分，但是我早就没有用这个了，时间太长基本都忘记了

**Comment by kingdom-l** [comment]
> > > > > > > > I have the same problem with you.I am in Ubuntu18.04,could you solved it?
> > > > > > > 
> > > > > > > 
> > > > > > > No, I really want to fix it! I need someone to help me
> > > > > > 
> > > > > > 
> > > > > > OK,we can keep in touch,If I solved I will tell you.
> > > > > 
> > > > > 
> > > > > OK.I'm also ubuntu18.04 system. I may also test it on ubuntu20.04 and I'll keep you informed when the results are available. Stay in touch and thank you for your cooperation
> > > > 
> > > > 
> > > > 秦志浩？
> > > 
> > > 
> > > > > yes,你是？
> > > > 
> > > > 
> > > > 我看你邮箱，觉得你是中国人，哈哈，我叫张新宇
> > > 
> > > 
> > > 哈哈，我看你的ubuntu界面有个zh，也觉得你是中国人，但你的英文有点不像。能加个qq吗
> > 
> > 
> > hello，你最终跑出来了吗？我卡在gazebo那部分“Run a Circle trajectory with correction”
> 
> 能出来一部分，但是我早就没有用这个了，时间太长基本都忘记了

好吧，我是能出一部分

**Comment by Wingflysky** [comment]
src.utils.visualization       trajectory_tracking_results
try:
        plt.draw()
        plt.pause(0.001) 
    except Exception as e:
        print(f"Error displaying plot: {str(e)}")
