### ISSUE TITLE
Direct Rotor Thrust Control

### ISSUE THREAD

**Issue by djhanove** [uzh-rpg/data_driven_mpc#4]
Upon changing the control mode from Body Rate Control to Rotor Thrust Control from "create_ros_gp_MPC.py"
`    

def optimize(self, model_data):

        w_opt, x_opt = self.quad_mpc.optimize(use_model=model_data, return_x=True)

        # Remember solution for next optimization
        self.last_w = self.quad_mpc.reshape_input_sequence(w_opt)

        next_control = ControlCommand()
        next_control.header = std_msgs.msg.Header()
        next_control.header.stamp = rospy.Time.now()
        next_control.control_mode = 4 # mode 2 = body rates, 4 = rotor thrusts
        next_control.armed = True
        next_control.collective_thrust = np.sum(w_opt[:4]) * self.quad.max_thrust / self.quad.mass
        next_control.bodyrates.x = x_opt[1, -3]
        next_control.bodyrates.y = x_opt[1, -2]
        next_control.bodyrates.z = x_opt[1, -1]
        next_control.rotor_thrusts = w_opt[:4]

        # Something is off with the colibri
        if self.quad_name == "colibri":
            next_control.collective_thrust -= 1.8

        return next_control, w_opt, x_opt`

The following segfault occurs
![image](https://user-images.githubusercontent.com/32501088/108815236-6987c280-75b4-11eb-8434-1c7c8c269183.png)

This occurs at the following line due to writing to an unallocated vector
![image](https://user-images.githubusercontent.com/32501088/108815318-89b78180-75b4-11eb-8b6d-595d502e5e95.png)

The segfault can be fixed by simply modifiying line 96 from indexing, to push_back
`desired_motor_speed.angular_velocities.push_back(sqrt(motor_speed_squared));`

In order to use individual rotor thrusts, we must scale the unit thrust command out of the MPC solution by the max thrust values of each motor i.e.
`        next_control.rotor_thrusts = w_opt[:4] * self.quad.max_thrust
`

However after scaling the MPC solution by the max thrust, the quad instantaneously flips over which makes me think there is likely a mismatch in configuration for the motor positions. 

I attempted to use just the unit thrust commands out the MPC, but the quad won't get off the ground which leads me to believe we need to both scale the unit thrust commands as well as make sure that the mapping for each motor is correct.

**Comment by tmguillem** [comment]
Hi @djhanove 

Thanks for using our code and helping debug the problem. I have implemented a fix in the following PR.
https://github.com/uzh-rpg/data_driven_mpc/pull/5

Regarding the bug from the `rpg_rotors_interface` package, a PR will also be issued asap.

**Comment by djhanove** [comment]
Confirmed, PR #5 fixes direct thrust control issues. Quad tracks reference trajectory identically with the body rate control method

**Comment by tmguillem** [comment]
Thanks, merged. Clossing issue.
